<a href="https://colab.research.google.com/github/Crissky/MLUD/blob/main/Aula%2002/comparacao_matriz_transposta.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Comparação da inserção da Matriz e da Matriz Transposta

## Imports

In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

## Carregando Base de Dados

In [2]:
!git clone https://github.com/Crissky/MLUD.git

fatal: destination path 'MLUD' already exists and is not an empty directory.


In [3]:
dataset = pd.read_csv('MLUD/Aula 02/admission.csv', delimiter=';')

## Visualizando os Dados

In [4]:
dataset

Name  GRE Score  TOEFL Score  ...  CGPA  Research  Approval
0    Lucas        337          118  ...  9.65         1         1
1      Ana        324          107  ...  8.87         1         1
2     Jose        316          104  ...  8.00         1         1
3   Carlos        322          110  ...  8.67         1         1
4  Zileide        314          103  ...  8.21         0         0
5    Joana        330          115  ...  9.34         1         1
6     Davi        321          109  ...  8.20         1         1
7   Daniel        308          101  ...  7.90         0         0
8  Marcelo        302          102  ...  8.00         0         0

[9 rows x 9 columns]

In [5]:
X = dataset.iloc[:,:-1].values        #Pegando somente as variáveis independentes

print(X)

[['Lucas' 337 118 4 4.5 4.5 9.65 1]
 ['Ana' 324 107 4 4.0 4.5 8.87 1]
 ['Jose' 316 104 3 3.0 3.5 8.0 1]
 ['Carlos' 322 110 3 3.5 2.5 8.67 1]
 ['Zileide' 314 103 2 2.0 3.0 8.21 0]
 ['Joana' 330 115 5 4.5 3.0 9.34 1]
 ['Davi' 321 109 3 3.0 4.0 8.2 1]
 ['Daniel' 308 101 2 3.0 4.0 7.9 0]
 ['Marcelo' 302 102 1 2.0 1.5 8.0 0]]


## Transformando os Nomes em Números

In [6]:
labelencoder_X = LabelEncoder()
X[:,0] = labelencoder_X.fit_transform(X[:,0])

print(X)

[[6 337 118 4 4.5 4.5 9.65 1]
 [0 324 107 4 4.0 4.5 8.87 1]
 [5 316 104 3 3.0 3.5 8.0 1]
 [1 322 110 3 3.5 2.5 8.67 1]
 [8 314 103 2 2.0 3.0 8.21 0]
 [4 330 115 5 4.5 3.0 9.34 1]
 [3 321 109 3 3.0 4.0 8.2 1]
 [2 308 101 2 3.0 4.0 7.9 0]
 [7 302 102 1 2.0 1.5 8.0 0]]


### Transformando os Labels Numéricos para One-Hot Encoding

One-Hot Encoding: uma lista de zeros e uns para que os Labels (Numéricos) não influenciem o treinamento.

In [7]:
D = pd.get_dummies(X[:,0])        # Criando o One-Hot Encoding com o Pandas

D

0  1  2  3  4  5  6  7  8
0  0  0  0  0  0  0  1  0  0
1  1  0  0  0  0  0  0  0  0
2  0  0  0  0  0  1  0  0  0
3  0  1  0  0  0  0  0  0  0
4  0  0  0  0  0  0  0  0  1
5  0  0  0  0  1  0  0  0  0
6  0  0  0  1  0  0  0  0  0
7  0  0  1  0  0  0  0  0  0
8  0  0  0  0  0  0  0  1  0

### Inserindo com a matriz normal

Linhas são as Colunas do Dataframe "D"

In [8]:
X = X[:, 1:]                                 # Retirando os Labels Numéricos
X2 = np.insert(X, 0, D.values, axis=1)       # Inserindo o One-Hot Encoding em X

X2

array([[0, 1, 0, 0, 0, 0, 0, 0, 0, 337, 118, 4, 4.5, 4.5, 9.65, 1],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 324, 107, 4, 4.0, 4.5, 8.87, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 316, 104, 3, 3.0, 3.5, 8.0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 322, 110, 3, 3.5, 2.5, 8.67, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 314, 103, 2, 2.0, 3.0, 8.21, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 330, 115, 5, 4.5, 3.0, 9.34, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 321, 109, 3, 3.0, 4.0, 8.2, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 308, 101, 2, 3.0, 4.0, 7.9, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 302, 102, 1, 2.0, 1.5, 8.0, 0]],
      dtype=object)

### Inserindo com a matriz transposta

Linhas são as mesmas do Dataframe "D"

In [9]:
X3 = np.insert(X, 0, D.values.T, axis=1)     # Inserindo o One-Hot Encoding em X

X3

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 337, 118, 4, 4.5, 4.5, 9.65, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 324, 107, 4, 4.0, 4.5, 8.87, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 316, 104, 3, 3.0, 3.5, 8.0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 322, 110, 3, 3.5, 2.5, 8.67, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 314, 103, 2, 2.0, 3.0, 8.21, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 330, 115, 5, 4.5, 3.0, 9.34, 1],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 321, 109, 3, 3.0, 4.0, 8.2, 1],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 308, 101, 2, 3.0, 4.0, 7.9, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 302, 102, 1, 2.0, 1.5, 8.0, 0]],
      dtype=object)