<a href="https://colab.research.google.com/github/Crissky/MLUD/blob/main/Aula%2003/normalizando_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Normalizando Conjunto de Dados
É necessário normalizar os dados quando há uma diferença muito grande nos valores das colunas, onde as com valores maiores seriam predominantes em ditar a classificação, diminuindo a relevâncias das com valores pequenos.

## Imports

In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

## Carregando Base de dados

In [2]:
!git clone https://github.com/Crissky/MLUD.git

Cloning into 'MLUD'...
remote: Enumerating objects: 50, done.
remote: Counting objects: 100% (50/50), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 50 (delta 12), reused 12 (delta 0), pack-reused 0
Unpacking objects: 100% (50/50), done.


In [3]:
dataset = pd.read_csv('MLUD/Aula03/admission.csv', delimiter=';')

## Visualizando os Dados

In [4]:
dataset.head()

Name  GRE Score  TOEFL Score  ...  CGPA  Research  Approval
0    Lucas        337          118  ...  9.65         1         1
1      Ana        324          107  ...  8.87         1         1
2     Jose        316          104  ...  8.00         1         1
3   Carlos        322          110  ...  8.67         1         1
4  Zileide        314          103  ...  8.21         0         0

[5 rows x 9 columns]

In [5]:
X = dataset.iloc[:,:-1].values              # Pegando somente as variáveis independentes
y = dataset.iloc[:,-1].values               # Pegando somente as variáveis dependentes
D = pd.get_dummies(X[:,0])                  # Criando o One-Hot Encoding com o Pandas (Ao usar o get_dummies o LabelEncoder não se faz necessário), pois ele funciona com strings)
X = X[:, 1:]                                # Retirando os Labels Numéricos
X = np.insert(X, 0, D.values.T, axis=1)     # Inserindo o One-Hot Encoding em X

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

D

Ana  Carlos  Daniel  Davi  Joana  Jose  Lucas  Marcelo  Zileide
0    0       0       0     0      0     0      1        0        0
1    1       0       0     0      0     0      0        0        0
2    0       0       0     0      0     1      0        0        0
3    0       1       0     0      0     0      0        0        0
4    0       0       0     0      0     0      0        0        1
5    0       0       0     0      1     0      0        0        0
6    0       0       0     1      0     0      0        0        0
7    0       0       1     0      0     0      0        0        0
8    0       0       0     0      0     0      0        1        0

In [6]:
print(X)

[[0 0 0 0 0 0 1 0 0 337 118 4 4.5 4.5 9.65 1]
 [1 0 0 0 0 0 0 0 0 324 107 4 4.0 4.5 8.87 1]
 [0 0 0 0 0 1 0 0 0 316 104 3 3.0 3.5 8.0 1]
 [0 1 0 0 0 0 0 0 0 322 110 3 3.5 2.5 8.67 1]
 [0 0 0 0 0 0 0 0 1 314 103 2 2.0 3.0 8.21 0]
 [0 0 0 0 1 0 0 0 0 330 115 5 4.5 3.0 9.34 1]
 [0 0 0 1 0 0 0 0 0 321 109 3 3.0 4.0 8.2 1]
 [0 0 1 0 0 0 0 0 0 308 101 2 3.0 4.0 7.9 0]
 [0 0 0 0 0 0 0 1 0 302 102 1 2.0 1.5 8.0 0]]


In [7]:
print(X_train)

[[0 0 0 1 0 0 0 0 0 321 109 3 3.0 4.0 8.2 1]
 [0 0 1 0 0 0 0 0 0 308 101 2 3.0 4.0 7.9 0]
 [0 0 0 0 1 0 0 0 0 330 115 5 4.5 3.0 9.34 1]
 [0 0 0 0 0 0 0 0 1 314 103 2 2.0 3.0 8.21 0]
 [0 0 0 0 0 1 0 0 0 316 104 3 3.0 3.5 8.0 1]
 [0 0 0 0 0 0 0 1 0 302 102 1 2.0 1.5 8.0 0]
 [0 1 0 0 0 0 0 0 0 322 110 3 3.5 2.5 8.67 1]]


## Normalizando os Dados

In [8]:
scale_X = StandardScaler()

X_train = scale_X.fit_transform(X_train)
X_test = scale_X.fit_transform(X_test)

In [9]:
print(X_train)

[[ 0.         -0.40824829 -0.40824829  2.44948974 -0.40824829 -0.40824829
   0.         -0.40824829 -0.40824829  0.56308063  0.56875012  0.24618298
   0.          1.13150476 -0.27754439  0.8660254 ]
 [ 0.         -0.40824829  2.44948974 -0.40824829 -0.40824829 -0.40824829
   0.         -0.40824829 -0.40824829 -0.94398811 -1.10756603 -0.61545745
   0.          1.13150476 -0.91106963 -1.15470054]
 [ 0.         -0.40824829 -0.40824829 -0.40824829  2.44948974 -0.40824829
   0.         -0.40824829 -0.40824829  1.6064359   1.82598724  1.96946386
   1.87082869 -0.08703883  2.12985152  0.8660254 ]
 [ 0.         -0.40824829 -0.40824829 -0.40824829 -0.40824829 -0.40824829
   0.         -0.40824829  2.44948974 -0.24841792 -0.68848699 -0.61545745
  -1.24721913 -0.08703883 -0.25642688 -1.15470054]
 [ 0.         -0.40824829 -0.40824829 -0.40824829 -0.40824829  2.44948974
   0.         -0.40824829 -0.40824829 -0.01656119 -0.47894747  0.24618298
   0.          0.52223297 -0.69989455  0.8660254 ]
 [ 0.

## Outra alternativa de Normalização

Valores ficarão entre zero e um.

In [10]:
new_ds = dataset.iloc[:,1:]                                 #Selecionando todas as colunas, menos a primeira pois é formada por strings
# dataset.iloc[:,1:] = (new_ds - new_ds.min()) / (new_ds.max() - new_ds.min())

(new_ds - new_ds.min()) / (new_ds.max() - new_ds.min())

GRE Score  TOEFL Score  University Rating  ...      CGPA  Research  Approval
0   1.000000     1.000000               0.75  ...  1.000000       1.0       1.0
1   0.628571     0.352941               0.75  ...  0.554286       1.0       1.0
2   0.400000     0.176471               0.50  ...  0.057143       1.0       1.0
3   0.571429     0.529412               0.50  ...  0.440000       1.0       1.0
4   0.342857     0.117647               0.25  ...  0.177143       0.0       0.0
5   0.800000     0.823529               1.00  ...  0.822857       1.0       1.0
6   0.542857     0.470588               0.50  ...  0.171429       1.0       1.0
7   0.171429     0.000000               0.25  ...  0.000000       0.0       0.0
8   0.000000     0.058824               0.00  ...  0.057143       0.0       0.0

[9 rows x 8 columns]

In [11]:
new_ds / new_ds.max()

GRE Score  TOEFL Score  University Rating  ...      CGPA  Research  Approval
0   1.000000     1.000000                0.8  ...  1.000000       1.0       1.0
1   0.961424     0.906780                0.8  ...  0.919171       1.0       1.0
2   0.937685     0.881356                0.6  ...  0.829016       1.0       1.0
3   0.955490     0.932203                0.6  ...  0.898446       1.0       1.0
4   0.931751     0.872881                0.4  ...  0.850777       0.0       0.0
5   0.979228     0.974576                1.0  ...  0.967876       1.0       1.0
6   0.952522     0.923729                0.6  ...  0.849741       1.0       1.0
7   0.913947     0.855932                0.4  ...  0.818653       0.0       0.0
8   0.896142     0.864407                0.2  ...  0.829016       0.0       0.0

[9 rows x 8 columns]